name: Test
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          environment: pr-${{ github.event.pull_request.number }}
          ref: ${{ github.ref }}
